name: wasteagram
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  image_picker: ^0.8.7
  transparent_image: ^2.0.1
  intl: ^0.18.0
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.16
  flutter_dotenv: ^5.0.2

dev_dependencies:
  test: ^1.22.0
  flutter_lints: ^2.0.0
  sentry_flutter: ^7.2.0

flutter:
  uses-material-design: true
  assets:
    - lib/.env
