name: journal
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.18
  intl: ^0.18.0
  sqflite: ^2.2.5
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/schema_1.sql.txt
    - lib/assets/schema_2.sql.txt
    - lib/assets/schema_3.sql.txt
