name: call_me_maybe

description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.9
  simple_ripple_animation: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/job_history.json
  fonts:
    - family: Sofia Pro
      fonts:
        - asset: assets/fonts/Sofia-Pro-Regular.otf
    - family: Sofia Pro Light
      fonts:
        - asset: assets/fonts/sofiapro-light.otf
    - family: Neue Haas
      fonts:
        - asset: assets/fonts/NeueHaasDisplayRoman.ttf
    - family: Dina
      fonts:
        - asset: assets/fonts/DinaRemasterII.ttc
